<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class StudentsSeeder extends Seeder
{
    public function run()
    {
        $students = [
            // 1ére année - Groupe A
            [
                'name' => 'Youssef Alaoui',
                'email' => 'youssef.alaoui@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2019-05-15',
                'birth_place' => 'Casablanca',
                'gender' => 'Masculin',
                'level' => '1ére année',
                'group' => 'A',
                'parent_name' => 'Ahmed Alaoui',
                'parent_cin' => 'AB123456',
                'address' => '123 Rue Hassan II, Casablanca',
                'phone' => '0661234567',
                'decision' => 'progress',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Salma Benhaddou',
                'email' => 'salma.benhaddou@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2019-07-23',
                'birth_place' => 'Rabat',
                'gender' => 'Féminin',
                'level' => '1ére année',
                'group' => 'A',
                'parent_name' => 'Karim Benhaddou',
                'parent_cin' => 'CD789012',
                'address' => '45 Avenue Mohammed V, Rabat',
                'phone' => '0662345678',
                'decision' => 'progress',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // 2ème année - Groupe B
            [
                'name' => 'Mehdi Tazi',
                'email' => 'mehdi.tazi@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2018-03-10',
                'birth_place' => 'Marrakech',
                'gender' => 'Masculin',
                'level' => '2ème année',
                'group' => 'B',
                'parent_name' => 'Nadia Tazi',
                'parent_cin' => 'EF345678',
                'address' => '78 Rue Majorelle, Marrakech',
                'phone' => '0663456789',
                'decision' => 'success',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leila Bennis',
                'email' => 'leila.bennis@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2018-09-05',
                'birth_place' => 'Fès',
                'gender' => 'Féminin',
                'level' => '2ème année',
                'group' => 'B',
                'parent_name' => 'Youssef Bennis',
                'parent_cin' => 'GH567890',
                'address' => '32 Rue des Almohades, Fès',
                'phone' => '0664567890',
                'decision' => 'progress',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // 3ème année - Groupe C
            [
                'name' => 'Omar Berrada',
                'email' => 'omar.berrada@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2017-11-30',
                'birth_place' => 'Tanger',
                'gender' => 'Masculin',
                'level' => '3ème année',
                'group' => 'C',
                'parent_name' => 'Fatima Berrada',
                'parent_cin' => 'IJ678901',
                'address' => '15 Avenue Pasteur, Tanger',
                'phone' => '0665678901',
                'decision' => 'success',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Amina Ziani',
                'email' => 'amina.ziani@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2017-04-18',
                'birth_place' => 'Agadir',
                'gender' => 'Féminin',
                'level' => '3ème année',
                'group' => 'C',
                'parent_name' => 'Mohammed Ziani',
                'parent_cin' => 'KL789012',
                'address' => '56 Boulevard Mohammed V, Agadir',
                'phone' => '0666789012',
                'decision' => 'success',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // 4ème année - Groupe A
            [
                'name' => 'Karim Ouazzani',
                'email' => 'karim.ouazzani@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2016-08-22',
                'birth_place' => 'Oujda',
                'gender' => 'Masculin',
                'level' => '4ème année',
                'group' => 'A',
                'parent_name' => 'Samira Ouazzani',
                'parent_cin' => 'MN890123',
                'address' => '89 Rue Ibn Batouta, Oujda',
                'phone' => '0667890123',
                'decision' => 'progress',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fatima El Fassi',
                'email' => 'fatima.elfassi@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2016-01-14',
                'birth_place' => 'Tétouan',
                'gender' => 'Féminin',
                'level' => '4ème année',
                'group' => 'A',
                'parent_name' => 'Hassan El Fassi',
                'parent_cin' => 'OP901234',
                'address' => '42 Avenue Mohammed VI, Tétouan',
                'phone' => '0668901234',
                'decision' => 'success',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // 5ème année - Groupe D
            [
                'name' => 'Ali Benjelloun',
                'email' => 'ali.benjelloun@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2015-06-03',
                'birth_place' => 'Meknès',
                'gender' => 'Masculin',
                'level' => '5ème année',
                'group' => 'D',
                'parent_name' => 'Naima Benjelloun',
                'parent_cin' => 'QR012345',
                'address' => '67 Rue El Mansour, Meknès',
                'phone' => '0669012345',
                'decision' => 'success',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nora Bensouda',
                'email' => 'nora.bensouda@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2015-09-25',
                'birth_place' => 'El Jadida',
                'gender' => 'Féminin',
                'level' => '5ème année',
                'group' => 'D',
                'parent_name' => 'Rachid Bensouda',
                'parent_cin' => 'ST123456',
                'address' => '23 Boulevard de la Corniche, El Jadida',
                'phone' => '0670123456',
                'decision' => 'progress',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // 6ème année - Groupe C
            [
                'name' => 'Hamza Lahlou',
                'email' => 'hamza.lahlou@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2014-12-08',
                'birth_place' => 'Khouribga',
                'gender' => 'Masculin',
                'level' => '6ème année',
                'group' => 'C',
                'parent_name' => 'Khalid Lahlou',
                'parent_cin' => 'UV234567',
                'address' => '54 Rue Ibn Sina, Khouribga',
                'phone' => '0671234567',
                'decision' => 'failed',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Souad Elamrani',
                'email' => 'souad.elamrani@gmail.com',
                'password' => Hash::make('123456789'),
                'birth_date' => '2014-02-19',
                'birth_place' => 'Essaouira',
                'gender' => 'Féminin',
                'level' => '6ème année',
                'group' => 'C',
                'parent_name' => 'Jamal Elamrani',
                'parent_cin' => 'WX345678',
                'address' => '29 Rue Moulay Ismail, Essaouira',
                'phone' => '0672345678',
                'decision' => 'success',
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('students')->insert($students);
    }
}